
enclave-file = "${home}/ccf/lib/libpdoenc.${enclave_file_type}"
enclave-type = "${enclave_type}"
consensus = "raft"
rpc-address = "${host_address}:6600"
node-address = "${host_address}:7700"

[join]
network-cert-file = "${ledger_key_root}/networkcert.pem"
target-rpc-address = "${ccf_pdotp_first_node_ip}:6600"