# Copyright Intel Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

dist: bionic
language: minimal

sudo: required
services:
  docker

addons:
  apt:
    packages:

env:
  global:
  matrix:
    # parallelize builds for the different interpreters
    - PDO_INTERPRETER=gipsy
    - PDO_INTERPRETER=wawaka
    - PDO_INTERPRETER=wawaka-opt

before_install:

script:
  # travis doesn't check out the branch itself but for our make to work we
  # need a branch or alike. So check create a local one ...
  - git checkout -b we-need-a-branch-for-below-to-work
  # do integration tests for all available interpreters (in SGX_MODE=SIM mode,
  # though, only ...)
  # jobs will be parallelized; mem config ignored for gipsy build
  - make WASM_MEM_CONFIG=MEDIUM -C docker test
