[Client]
Identity = "${identity}"

[Sawtooth]
LedgerURL = "http://intsim-t1.jf.intel.com:8008/"

[Service]
EnclaveServiceDatabaseFile = "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/data/eservice-db.json"

[Replication]
NumProvableReplicas = 0
Duration = 120

[Contract]
DataDirectory = "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/data"
SourceSearchPath = [ ".", "./contracts", "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/contracts",]
Name = "test-contract"
SourceFile = "./test-contract.b64"

[Logging]
LogLevel = "INFO"
LogFile = "__screen__"

[Key]
SearchPath = [ ".", "./keys", "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/keys",]
FileName = "${identity}_private.pem"

[Bindings]
data = "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/data"
save = "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo/data/__contract_cache__"
home = "/home/mbowman/dev/pdo-test-env/_dev/opt/pdo"
base = "${base}"
identity = "${identity}"
