#!/bin/bash

# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

../bin/pdo-cli json --keyfile key-enclave.priv --wait 10 enclave-register-with-simulated-proof-data.json
../bin/pdo-cli json --keyfile key-enclave.priv --wait 10 enclave-register-without-proof-data.json

../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 contract-register.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 contract-add-enclave-1.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key-2.priv --wait 10 contract-add-enclave-2.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key-2.priv --wait 10 contract-remove-enclave-2.json

../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 ccl-initialize.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 ccl-update-AB.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 ccl-update-BC.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 ccl-update-CD.json
../bin/pdo-cli json --keyfile key-contract.priv --enclave-keyfile enclave-signing-key.priv --wait 10 ccl-terminate.json
