# big state tests
'(big-state 100 (value "0"))
'(big-state 110 (value "1"))
'(big-state 120 (value "2"))
'(big-state 130 (value "3"))
'(big-state 140 (value "4"))
'(big-state 150 (value "5"))
'(big-state 160 (value "6"))
'(big-state 170 (value "7"))
'(big-state 180 (value "8")),intrinsic state size exceeds maximum,fail
'(big-state 190 (value "9")),intrinsic state size exceeds maximum,fail
# run one deep recursion test to make sure the enclave is not corrupted
'(deep-recursion 1000),1000
# deep recursion tests
'(clear-state)
'(deep-recursion 2000),2000
'(deep-recursion 3000),3000
'(deep-recursion 4000),4000
'(deep-recursion 5000),5000
'(deep-recursion 6000),6000
'(deep-recursion 7000),7000
'(deep-recursion 8000),8000
'(deep-recursion 9000),9000
'(deep-recursion 10000),10000
'(deep-recursion 11000),11000
'(deep-recursion 12000),12000
'(deep-recursion 13000),13000
'(deep-recursion 14000),14000
'(deep-recursion 15000),excessive memory use,fail
# run one deep recursion test to make sure the enclave is not corrupted
'(deep-recursion 1000),1000
# the quotes around the string are part of the result
'(big-value 1000 (key "big-value") (value-base "b")), "b{1000}"
'(big-value 2000 (key "big-value") (value-base "b")), "b{2000}"
'(big-value 4000 (key "big-value") (value-base "b")), "b{4000}"
'(big-value 8000 (key "big-value") (value-base "b")), "b{8000}"
'(big-value 16000 (key "big-value") (value-base "b")), "b{16000}"
'(big-value 32000 (key "big-value") (value-base "b")), "b{32000}"
'(big-value 64000 (key "big-value") (value-base "b")), "b{64000}"
# run one deep recursion test to make sure the enclave is not corrupted
'(deep-recursion 1000),1000
'(many-keys 1000 (key-base "a") (value "v")), #t
'(many-keys 2000 (key-base "b") (value "v")), #t
'(many-keys 4000 (key-base "c") (value "v")), #t
'(many-keys 8000 (key-base "d") (value "v")), #t
'(many-keys 16000 (key-base "e") (value "v")), #t
'(many-keys 32000 (key-base "f") (value "v")), #t
'(many-keys 64000 (key-base "g") (value "v")), #t
'(many-keys 64000 (key-base "g") (value "n")), #t
# run one deep recursion test to make sure the enclave is not corrupted
'(deep-recursion 1000),1000
