'(big-state 100 (value "a")), #t
'(big-state 100 (value "b")), #t
'(big-state 100 (value "c")), #t
'(big-state 100 (value "d")), #t
'(big-state 100 (value "e")), #t
'(big-state 100 (value "f")), #t
'(big-state 100 (value "g")), #t
'(big-state 100 (value "h")), #t
'(big-state 100 (value "i")), #t
'(big-state 100 (value "j")), #t
'(big-state 100 (value "k")), #t
# this is necessary to clear state or later calls fail
'(clear-state), #t
'(deep-recursion 10), 10
# the quotes around the string are part of the result
'(big-value 10 (key "big-value") (value-base "b")), "bbbbbbbbbb"
'(many-keys 10 (key-base "many-keys") (value "m")), #t
