# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdo_contract_enclave_registry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdo_contract_enclave_registry.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n#pdo_contract_enclave_registry.proto\"\xa7\x01\n\x16PdoContractEnclaveInfo\x12\x15\n\rverifying_key\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncryption_key\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\t\x12\'\n\x1flast_registration_block_context\x18\x04 \x01(\t\x12#\n\x1bregistration_transaction_id\x18\x05 \x01(\t\"a\n\x1dPdoContractEnclaveTransaction\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x15\n\rverifying_key\x18\x02 \x01(\t\x12\x1b\n\x13transaction_details\x18\x03 \x01(\x0c\"\xa8\x01\n\x1aPdoContractEnclaveRegister\x12\x1b\n\x13organizational_info\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncryption_key\x18\x02 \x01(\t\x12\x12\n\nproof_data\x18\x03 \x01(\t\x12\x1d\n\x15\x65nclave_persistent_id\x18\x04 \x01(\t\x12\"\n\x1aregistration_block_context\x18\x05 \x01(\t\">\n\x18PdoContractEnclaveUpdate\x12\"\n\x1aregistration_block_context\x18\x01 \x01(\tB\x19\n\x15pdo.sawtooth.protobufP\x01\x62\x06proto3')
)




_PDOCONTRACTENCLAVEINFO = _descriptor.Descriptor(
  name='PdoContractEnclaveInfo',
  full_name='PdoContractEnclaveInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verifying_key', full_name='PdoContractEnclaveInfo.verifying_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryption_key', full_name='PdoContractEnclaveInfo.encryption_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='PdoContractEnclaveInfo.owner_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_registration_block_context', full_name='PdoContractEnclaveInfo.last_registration_block_context', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='registration_transaction_id', full_name='PdoContractEnclaveInfo.registration_transaction_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=207,
)


_PDOCONTRACTENCLAVETRANSACTION = _descriptor.Descriptor(
  name='PdoContractEnclaveTransaction',
  full_name='PdoContractEnclaveTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='PdoContractEnclaveTransaction.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verifying_key', full_name='PdoContractEnclaveTransaction.verifying_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transaction_details', full_name='PdoContractEnclaveTransaction.transaction_details', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=306,
)


_PDOCONTRACTENCLAVEREGISTER = _descriptor.Descriptor(
  name='PdoContractEnclaveRegister',
  full_name='PdoContractEnclaveRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizational_info', full_name='PdoContractEnclaveRegister.organizational_info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encryption_key', full_name='PdoContractEnclaveRegister.encryption_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proof_data', full_name='PdoContractEnclaveRegister.proof_data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enclave_persistent_id', full_name='PdoContractEnclaveRegister.enclave_persistent_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='registration_block_context', full_name='PdoContractEnclaveRegister.registration_block_context', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=477,
)


_PDOCONTRACTENCLAVEUPDATE = _descriptor.Descriptor(
  name='PdoContractEnclaveUpdate',
  full_name='PdoContractEnclaveUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_block_context', full_name='PdoContractEnclaveUpdate.registration_block_context', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=541,
)

DESCRIPTOR.message_types_by_name['PdoContractEnclaveInfo'] = _PDOCONTRACTENCLAVEINFO
DESCRIPTOR.message_types_by_name['PdoContractEnclaveTransaction'] = _PDOCONTRACTENCLAVETRANSACTION
DESCRIPTOR.message_types_by_name['PdoContractEnclaveRegister'] = _PDOCONTRACTENCLAVEREGISTER
DESCRIPTOR.message_types_by_name['PdoContractEnclaveUpdate'] = _PDOCONTRACTENCLAVEUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PdoContractEnclaveInfo = _reflection.GeneratedProtocolMessageType('PdoContractEnclaveInfo', (_message.Message,), dict(
  DESCRIPTOR = _PDOCONTRACTENCLAVEINFO,
  __module__ = 'pdo_contract_enclave_registry_pb2'
  # @@protoc_insertion_point(class_scope:PdoContractEnclaveInfo)
  ))
_sym_db.RegisterMessage(PdoContractEnclaveInfo)

PdoContractEnclaveTransaction = _reflection.GeneratedProtocolMessageType('PdoContractEnclaveTransaction', (_message.Message,), dict(
  DESCRIPTOR = _PDOCONTRACTENCLAVETRANSACTION,
  __module__ = 'pdo_contract_enclave_registry_pb2'
  # @@protoc_insertion_point(class_scope:PdoContractEnclaveTransaction)
  ))
_sym_db.RegisterMessage(PdoContractEnclaveTransaction)

PdoContractEnclaveRegister = _reflection.GeneratedProtocolMessageType('PdoContractEnclaveRegister', (_message.Message,), dict(
  DESCRIPTOR = _PDOCONTRACTENCLAVEREGISTER,
  __module__ = 'pdo_contract_enclave_registry_pb2'
  # @@protoc_insertion_point(class_scope:PdoContractEnclaveRegister)
  ))
_sym_db.RegisterMessage(PdoContractEnclaveRegister)

PdoContractEnclaveUpdate = _reflection.GeneratedProtocolMessageType('PdoContractEnclaveUpdate', (_message.Message,), dict(
  DESCRIPTOR = _PDOCONTRACTENCLAVEUPDATE,
  __module__ = 'pdo_contract_enclave_registry_pb2'
  # @@protoc_insertion_point(class_scope:PdoContractEnclaveUpdate)
  ))
_sym_db.RegisterMessage(PdoContractEnclaveUpdate)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025pdo.sawtooth.protobufP\001'))
# @@protoc_insertion_point(module_scope)
