# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pdo_contract_ccl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pdo_contract_ccl.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16pdo_contract_ccl.proto\"\xcc\x01\n\x17\x43\x43L_ContractStateUpdate\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63urrent_state_hash\x18\x02 \x01(\t\x12\x1b\n\x13previous_state_hash\x18\x03 \x01(\t\x12\x14\n\x0cmessage_hash\x18\x04 \x01(\t\x12\x17\n\x0f\x65ncrypted_state\x18\x05 \x01(\t\x12\x34\n\x0f\x64\x65pendency_list\x18\x06 \x03(\x0b\x32\x1b.CCL_ContractStateReference\"E\n\x1a\x43\x43L_ContractStateReference\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\t\x12\x12\n\nstate_hash\x18\x02 \x01(\t\"[\n\x11\x43\x43L_ContractState\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12.\n\x0cstate_update\x18\x02 \x01(\x0b\x32\x18.CCL_ContractStateUpdate\"u\n\x17\x43\x43L_ContractInformation\x12\x13\n\x0b\x63ontract_id\x18\x01 \x01(\t\x12\x32\n\rcurrent_state\x18\x02 \x01(\x0b\x32\x1b.CCL_ContractStateReference\x12\x11\n\tis_active\x18\x03 \x01(\x08\"\xc2\x01\n\x16\x43\x43L_TransactionPayload\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x1b\n\x13\x63ontract_enclave_id\x18\x02 \x01(\t\x12\"\n\x1a\x63ontract_enclave_signature\x18\x03 \x01(\t\x12\x12\n\nchannel_id\x18\x04 \x01(\t\x12.\n\x0cstate_update\x18\x05 \x01(\x0b\x32\x18.CCL_ContractStateUpdate\x12\x15\n\rpdo_signature\x18\x06 \x01(\tB\x19\n\x15pdo.sawtooth.protobufP\x01\x62\x06proto3')
)




_CCL_CONTRACTSTATEUPDATE = _descriptor.Descriptor(
  name='CCL_ContractStateUpdate',
  full_name='CCL_ContractStateUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='CCL_ContractStateUpdate.contract_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_state_hash', full_name='CCL_ContractStateUpdate.current_state_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='previous_state_hash', full_name='CCL_ContractStateUpdate.previous_state_hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_hash', full_name='CCL_ContractStateUpdate.message_hash', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encrypted_state', full_name='CCL_ContractStateUpdate.encrypted_state', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependency_list', full_name='CCL_ContractStateUpdate.dependency_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=231,
)


_CCL_CONTRACTSTATEREFERENCE = _descriptor.Descriptor(
  name='CCL_ContractStateReference',
  full_name='CCL_ContractStateReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='CCL_ContractStateReference.contract_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_hash', full_name='CCL_ContractStateReference.state_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=302,
)


_CCL_CONTRACTSTATE = _descriptor.Descriptor(
  name='CCL_ContractState',
  full_name='CCL_ContractState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='CCL_ContractState.transaction_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_update', full_name='CCL_ContractState.state_update', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=395,
)


_CCL_CONTRACTINFORMATION = _descriptor.Descriptor(
  name='CCL_ContractInformation',
  full_name='CCL_ContractInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='CCL_ContractInformation.contract_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_state', full_name='CCL_ContractInformation.current_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_active', full_name='CCL_ContractInformation.is_active', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=514,
)


_CCL_TRANSACTIONPAYLOAD = _descriptor.Descriptor(
  name='CCL_TransactionPayload',
  full_name='CCL_TransactionPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='verb', full_name='CCL_TransactionPayload.verb', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract_enclave_id', full_name='CCL_TransactionPayload.contract_enclave_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract_enclave_signature', full_name='CCL_TransactionPayload.contract_enclave_signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='CCL_TransactionPayload.channel_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_update', full_name='CCL_TransactionPayload.state_update', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pdo_signature', full_name='CCL_TransactionPayload.pdo_signature', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=711,
)

_CCL_CONTRACTSTATEUPDATE.fields_by_name['dependency_list'].message_type = _CCL_CONTRACTSTATEREFERENCE
_CCL_CONTRACTSTATE.fields_by_name['state_update'].message_type = _CCL_CONTRACTSTATEUPDATE
_CCL_CONTRACTINFORMATION.fields_by_name['current_state'].message_type = _CCL_CONTRACTSTATEREFERENCE
_CCL_TRANSACTIONPAYLOAD.fields_by_name['state_update'].message_type = _CCL_CONTRACTSTATEUPDATE
DESCRIPTOR.message_types_by_name['CCL_ContractStateUpdate'] = _CCL_CONTRACTSTATEUPDATE
DESCRIPTOR.message_types_by_name['CCL_ContractStateReference'] = _CCL_CONTRACTSTATEREFERENCE
DESCRIPTOR.message_types_by_name['CCL_ContractState'] = _CCL_CONTRACTSTATE
DESCRIPTOR.message_types_by_name['CCL_ContractInformation'] = _CCL_CONTRACTINFORMATION
DESCRIPTOR.message_types_by_name['CCL_TransactionPayload'] = _CCL_TRANSACTIONPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CCL_ContractStateUpdate = _reflection.GeneratedProtocolMessageType('CCL_ContractStateUpdate', (_message.Message,), dict(
  DESCRIPTOR = _CCL_CONTRACTSTATEUPDATE,
  __module__ = 'pdo_contract_ccl_pb2'
  # @@protoc_insertion_point(class_scope:CCL_ContractStateUpdate)
  ))
_sym_db.RegisterMessage(CCL_ContractStateUpdate)

CCL_ContractStateReference = _reflection.GeneratedProtocolMessageType('CCL_ContractStateReference', (_message.Message,), dict(
  DESCRIPTOR = _CCL_CONTRACTSTATEREFERENCE,
  __module__ = 'pdo_contract_ccl_pb2'
  # @@protoc_insertion_point(class_scope:CCL_ContractStateReference)
  ))
_sym_db.RegisterMessage(CCL_ContractStateReference)

CCL_ContractState = _reflection.GeneratedProtocolMessageType('CCL_ContractState', (_message.Message,), dict(
  DESCRIPTOR = _CCL_CONTRACTSTATE,
  __module__ = 'pdo_contract_ccl_pb2'
  # @@protoc_insertion_point(class_scope:CCL_ContractState)
  ))
_sym_db.RegisterMessage(CCL_ContractState)

CCL_ContractInformation = _reflection.GeneratedProtocolMessageType('CCL_ContractInformation', (_message.Message,), dict(
  DESCRIPTOR = _CCL_CONTRACTINFORMATION,
  __module__ = 'pdo_contract_ccl_pb2'
  # @@protoc_insertion_point(class_scope:CCL_ContractInformation)
  ))
_sym_db.RegisterMessage(CCL_ContractInformation)

CCL_TransactionPayload = _reflection.GeneratedProtocolMessageType('CCL_TransactionPayload', (_message.Message,), dict(
  DESCRIPTOR = _CCL_TRANSACTIONPAYLOAD,
  __module__ = 'pdo_contract_ccl_pb2'
  # @@protoc_insertion_point(class_scope:CCL_TransactionPayload)
  ))
_sym_db.RegisterMessage(CCL_TransactionPayload)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025pdo.sawtooth.protobufP\001'))
# @@protoc_insertion_point(module_scope)
